[package]
name = "manimrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "manimrust"
crate-type = ["cdylib"]

[dependencies]
num-traits = "0.2.19"
numpy = "0.21.0"
pyo3 = "0.21.1"
